services:
  - type: web
    name: woodcraft-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: BRAND_NAME
        value: WoodCraft Wonders
      # Compute the public URL for absolute assets in emails
      - key: BASE_URL
        fromService:
          name: woodcraft-api
          type: web
          property: url
      - key: PUBLIC_BASE_URL
        fromService:
          name: woodcraft-api
          type: web
          property: url
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/server/uploads
        sizeGB: 1

  - type: static
    name: woodcraft-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_BASE
        fromService:
          name: woodcraft-api
          type: web
          property: url
